# Generated by Django 4.1.3 on 2022-11-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="notes",
            field=models.TextField(default="", max_length=300),
            preserve_default=False,
        ),
    ]
